import React, { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Typography, Spacing } from '@/components/ui/design-system';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Brain, 
  Sparkles, 
  Zap, 
  Search,
  FileText,
  Tag,
  MessageCircle,
  PlusCircle,
  Focus,
  TrendingUp,
  Mic,
  BarChart3,
  Target,
  BookOpen,
  BellRing,
  MapPin,
  Eye,
  Edit3,
  Users
} from 'lucide-react';

// Import all feature components
import { QuickNoteCapture } from '@/components/features/QuickNoteCapture';
import { ContentRecommendationEngine } from '@/components/features/ContentRecommendationEngine';
import { AIContentSummarizer } from '@/components/features/AIContentSummarizer';
import { PersonalKnowledgeAssistant } from '@/components/features/PersonalKnowledgeAssistant';
import { VoiceSearchInterface } from '@/components/features/VoiceSearchInterface';
import { SmartTaggingSystem } from '@/components/features/SmartTaggingSystem';
import { AIContentAnalysis } from '@/components/features/AIContentAnalysis';
import { ReadingProgressTracker } from '@/components/features/ReadingProgressTracker';
import { AILearningPathGenerator } from '@/components/features/AILearningPathGenerator';
import { SmartNotifications } from '@/components/features/SmartNotifications';
import { AIInsightsWidget } from '@/components/features/AIInsightsWidget';
import { AIWritingAssistant } from '@/components/features/AIWritingAssistant';
import { AIKnowledgeGraph } from '@/components/features/AIKnowledgeGraph';
import { AIStudyBuddy } from '@/components/features/AIStudyBuddy';

const Features: React.FC = () => {
  const [activeDemo, setActiveDemo] = useState<string | null>(null);

  const features = [
    {
      id: 'quick-capture',
      title: 'Quick Note Capture',
      description: 'Instantly capture thoughts, ideas, and content with smart organization',
      icon: PlusCircle,
      category: 'Core',
      component: QuickNoteCapture,
      highlights: ['Voice input', 'Auto-tagging', 'Quick templates']
    },
    {
      id: 'ai-assistant',
      title: 'Personal Knowledge Assistant',
      description: 'Chat with your knowledge base using natural language queries',
      icon: MessageCircle,
      category: 'AI',
      component: PersonalKnowledgeAssistant,
      highlights: ['Natural language', 'Context-aware', 'Smart suggestions']
    },
    {
      id: 'content-summarizer',
      title: 'AI Content Summarizer',
      description: 'Generate intelligent summaries and extract key insights',
      icon: FileText,
      category: 'AI',
      component: AIContentSummarizer,
      highlights: ['Multiple formats', 'Key points', 'Reading time']
    },
    {
      id: 'voice-search',
      title: 'Voice Search Interface',
      description: 'Search your content using natural voice commands',
      icon: Mic,
      category: 'AI',
      component: VoiceSearchInterface,
      highlights: ['Voice recognition', 'Natural queries', 'Hands-free']
    },
    {
      id: 'smart-tagging',
      title: 'Smart Tagging System',
      description: 'Automatic content categorization with AI suggestions',
      icon: Tag,
      category: 'AI',
      component: SmartTaggingSystem,
      highlights: ['Auto-suggestions', 'Trending tags', 'Smart organization']
    },
    {
      id: 'content-analysis',
      title: 'AI Content Analysis',
      description: 'Deep insights into your knowledge patterns and gaps',
      icon: BarChart3,
      category: 'Analytics',
      component: AIContentAnalysis,
      highlights: ['Pattern recognition', 'Knowledge gaps', 'Productivity score']
    },
    {
      id: 'reading-tracker',
      title: 'Reading Progress Tracker',
      description: 'Monitor your learning journey with detailed analytics',
      icon: BookOpen,
      category: 'Analytics',
      component: ReadingProgressTracker,
      highlights: ['Progress tracking', 'Goals', 'Achievements']
    },
    {
      id: 'learning-paths',
      title: 'AI Learning Path Generator',
      description: 'Personalized learning roadmaps generated by AI',
      icon: Target,
      category: 'AI',
      component: AILearningPathGenerator,
      highlights: ['Personalized paths', 'Step-by-step', 'Progress tracking']
    },
    {
      id: 'recommendations',
      title: 'Content Recommendation Engine',
      description: 'Discover relevant content based on your interests',
      icon: TrendingUp,
      category: 'AI',
      component: ContentRecommendationEngine,
      highlights: ['Smart recommendations', 'Learning goals', 'Trending content']
    },
    {
      id: 'smart-notifications',
      title: 'Smart Notifications',
      description: 'Intelligent alerts and reminders for optimal learning',
      icon: BellRing,
      category: 'Productivity',
      component: SmartNotifications,
      highlights: ['Context-aware', 'Learning reminders', 'Priority-based']
    },
    {
      id: 'writing-assistant',
      title: 'AI Writing Assistant',
      description: 'Enhance, summarize, expand, and improve your writing with AI',
      icon: Edit3,
      category: 'AI',
      component: AIWritingAssistant,
      highlights: ['Improve writing', 'Summarize text', 'Expand ideas', 'Simplify content']
    },
    {
      id: 'ai-insights',
      title: 'AI Insights Widget',
      description: 'Real-time AI-powered insights about your learning patterns',
      icon: Brain,
      category: 'AI',
      component: AIInsightsWidget,
      highlights: ['Pattern detection', 'Smart recommendations', 'Live insights']
    },
    {
      id: 'knowledge-graph',
      title: 'AI Knowledge Graph',
      description: 'Visualize connections between your knowledge and skills',
      icon: MapPin,
      category: 'AI',
      component: AIKnowledgeGraph,
      highlights: ['Interactive visualization', 'Knowledge mapping', 'Skill tracking']
    },
    {
      id: 'study-buddy',
      title: 'AI Study Buddy',
      description: 'Collaborative learning with AI-powered insights and social features',
      icon: Users,
      category: 'AI',
      component: AIStudyBuddy,
      highlights: ['Social learning', 'Study sessions', 'Achievement tracking']
    }
  ];

  const categories = ['All', 'Core', 'AI', 'Analytics', 'Productivity'];
  const [selectedCategory, setSelectedCategory] = useState('All');

  const filteredFeatures = selectedCategory === 'All' 
    ? features 
    : features.filter(f => f.category === selectedCategory);

  const aiFeatures = features.filter(f => f.category === 'AI');

  const renderDemo = () => {
    const feature = features.find(f => f.id === activeDemo);
    if (!feature) return null;
    
    const Component = feature.component;
    return (
      <div className="mt-8">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <feature.icon className="h-6 w-6 text-primary" />
            <Typography.H3>{feature.title}</Typography.H3>
            <Badge variant="secondary">{feature.category}</Badge>
          </div>
          <Button variant="outline" onClick={() => setActiveDemo(null)}>
            Close Demo
          </Button>
        </div>
        <Component />
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-background">
      <Helmet>
        <title>Features - Accio</title>
        <meta name="description" content="Explore powerful features for intelligent knowledge management and AI-driven productivity." />
      </Helmet>

      <Spacing.Section size="lg">
        <Spacing.Container>
          <div className="max-w-7xl mx-auto">
            {/* Header */}
            <div className="text-center mb-12">
              <Typography.H1 className="mb-4">
                Intelligent Features for Modern Knowledge Workers
              </Typography.H1>
              <Typography.Lead>
                Discover how AI transforms your workflow with smart capture, analysis, and discovery tools
              </Typography.Lead>
            </div>

            {activeDemo ? (
              renderDemo()
            ) : (
              <>
                {/* AI Features Highlight */}
                <Card className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 mb-12">
                  <CardContent className="p-8">
                    <div className="text-center">
                      <Brain className="h-12 w-12 text-primary mx-auto mb-4" />
                      <Typography.H2 className="mb-4">AI-Powered Intelligence</Typography.H2>
                      <Typography.P className="text-muted-foreground mb-6 max-w-2xl mx-auto">
                        Experience the next generation of knowledge management with {features.filter(f => f.category === 'AI').length} AI-driven features 
                        that understand your content, learn from your patterns, and enhance your productivity.
                      </Typography.P>
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto">
                        <div className="text-center">
                          <Sparkles className="h-8 w-8 text-primary mx-auto mb-2" />
                          <h4 className="font-medium">Smart Analysis</h4>
                          <p className="text-sm text-muted-foreground">AI understands and categorizes your content</p>
                        </div>
                        <div className="text-center">
                          <Search className="h-8 w-8 text-primary mx-auto mb-2" />
                          <h4 className="font-medium">Natural Language</h4>
                          <p className="text-sm text-muted-foreground">Search and interact using everyday language</p>
                        </div>
                        <div className="text-center">
                          <TrendingUp className="h-8 w-8 text-primary mx-auto mb-2" />
                          <h4 className="font-medium">Personalized Learning</h4>
                          <p className="text-sm text-muted-foreground">Recommendations tailored to your goals</p>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Category Filter */}
                <div className="flex flex-wrap justify-center gap-2 mb-8">
                  {categories.map((category) => (
                    <Button
                      key={category}
                      variant={selectedCategory === category ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => setSelectedCategory(category)}
                    >
                      {category}
                      {category !== 'All' && (
                        <Badge variant="secondary" className="ml-2">
                          {features.filter(f => f.category === category).length}
                        </Badge>
                      )}
                    </Button>
                  ))}
                </div>

                {/* Features Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {filteredFeatures.map((feature) => {
                    const Icon = feature.icon;
                    const isAI = feature.category === 'AI';
                    
                    return (
                      <Card key={feature.id} className={`hover:shadow-lg transition-all duration-300 cursor-pointer group ${isAI ? 'ring-1 ring-primary/20' : ''}`}>
                        <CardHeader>
                          <div className="flex items-center gap-3 mb-2">
                            <div className={`p-2 rounded-lg group-hover:scale-110 transition-transform ${isAI ? 'bg-primary/20' : 'bg-muted'}`}>
                              <Icon className={`h-5 w-5 ${isAI ? 'text-primary' : 'text-muted-foreground'}`} />
                            </div>
                            <Badge variant={isAI ? 'default' : 'secondary'}>
                              {feature.category}
                              {isAI && <Sparkles className="h-3 w-3 ml-1" />}
                            </Badge>
                          </div>
                          <CardTitle className="text-lg">{feature.title}</CardTitle>
                        </CardHeader>
                        <CardContent>
                          <p className="text-muted-foreground mb-4">{feature.description}</p>
                          
                          <div className="space-y-3">
                            <div className="flex flex-wrap gap-1">
                              {feature.highlights.map((highlight, index) => (
                                <Badge key={index} variant="outline" className="text-xs">
                                  {highlight}
                                </Badge>
                              ))}
                            </div>
                            
                            <Button 
                              onClick={() => setActiveDemo(feature.id)}
                              className="w-full gap-2"
                              variant={isAI ? 'default' : 'outline'}
                            >
                              {isAI ? <Zap className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                              Try Interactive Demo
                            </Button>
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })}
                </div>

                {/* Feature Stats */}
                <div className="mt-12 text-center">
                  <Typography.H3 className="mb-6">Built for Power Users</Typography.H3>
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-6 max-w-4xl mx-auto">
                    <div className="text-center">
                      <div className="text-3xl font-bold text-primary">{features.length}</div>
                      <div className="text-sm text-muted-foreground">Total Features</div>
                    </div>
                    <div className="text-center">
                      <div className="text-3xl font-bold text-primary">{features.filter(f => f.category === 'AI').length}</div>
                      <div className="text-sm text-muted-foreground">AI-Powered</div>
                    </div>
                    <div className="text-center">
                      <div className="text-3xl font-bold text-primary">5</div>
                      <div className="text-sm text-muted-foreground">Categories</div>
                    </div>
                    <div className="text-center">
                      <div className="text-3xl font-bold text-primary">100%</div>
                      <div className="text-sm text-muted-foreground">Interactive</div>
                    </div>
                  </div>
                </div>
              </>
            )}
          </div>
        </Spacing.Container>
      </Spacing.Section>

      {/* Background AI Components */}
      <AIInsightsWidget />
      <SmartNotifications />
    </div>
  );
};

export default Features;
