
import React from 'react';
import { Card } from '@/components/ui/card';
import { Link, FileText, Search, Tag } from 'lucide-react';

const FeaturesSection = () => {
  return (
    <section className="py-16 px-4 bg-secondary" aria-labelledby="features-heading">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <h2 id="features-heading" className="text-3xl font-bold mb-4">Powerful Features</h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Accio brings powerful tools to help you organize and retrieve your digital content
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 gap-8">
          <Card className="p-6 card-hover shadow-sm transition-all">
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-2">
              <Search className="h-5 w-5 text-primary" aria-hidden="true" />
              Natural Language Search
            </h3>
            <p className="text-muted-foreground">
              Ask questions in plain English like "What did I save about job interviews?" and Accio will find the right content.
            </p>
          </Card>
          
          <Card className="p-6 card-hover shadow-sm transition-all">
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-2">
              <Tag className="h-5 w-5 text-primary" aria-hidden="true" />
              AI-Powered Tagging
            </h3>
            <p className="text-muted-foreground">
              Automatically categorize your content with relevant tags generated by advanced AI.
            </p>
          </Card>
          
          <Card className="p-6 card-hover shadow-sm transition-all">
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" aria-hidden="true" />
              Multiple Content Types
            </h3>
            <p className="text-muted-foreground">
              Save links, upload PDFs, or add images - all in one organized library.
            </p>
          </Card>
          
          <Card className="p-6 card-hover shadow-sm transition-all">
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-2">
              <Link className="h-5 w-5 text-primary" aria-hidden="true" />
              One-Click Saving
            </h3>
            <p className="text-muted-foreground">
              Save content from anywhere with a simple click or share from other apps.
            </p>
          </Card>
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
