
export const copy = {
  common: {
    required: 'Required field',
    optional: 'Optional',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    reset: 'Reset',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    clear: 'Clear',
    selectAll: 'Select All',
    deselectAll: 'Deselect All'
  },
  accessibility: {
    skipToContent: 'Skip to main content',
    skipToNavigation: 'Skip to navigation',
    skipToFooter: 'Skip to footer',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    toggleMenu: 'Toggle menu',
    currentPage: 'Current page',
    openInNewTab: 'Opens in new tab',
    required: 'Required',
    optional: 'Optional',
    expandSection: 'Expand section',
    collapseSection: 'Collapse section',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    removeFilter: 'Remove filter',
    loadingContent: 'Loading content',
    errorLoadingContent: 'Error loading content',
    noResultsFound: 'No results found',
    searchResults: 'Search results',
    pageNavigation: 'Page navigation',
    breadcrumbNavigation: 'Breadcrumb navigation',
    socialMediaLinks: 'Social media links',
    contactInformation: 'Contact information',
    copyrightNotice: 'Copyright notice'
  },
  forms: {
    validation: {
      required: 'This field is required',
      email: 'Please enter a valid email address',
      password: 'Password must be at least 8 characters',
      passwordMatch: 'Passwords do not match',
      minLength: 'Must be at least {min} characters',
      maxLength: 'Must be no more than {max} characters',
      invalidFormat: 'Invalid format'
    }
  }
};
