
export default {
  common: {
    skip_to_content: "Skip to content",
    theme: {
      change: "Change theme",
      light: "Light",
      dark: "Dark",
      system: "System",
      current: "Current theme is {{theme}}"
    },
    language: {
      change: "Change language",
      en: "English",
      ar: "العربية",
      he: "עברית"
    }
  },
  auth: {
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email",
    password: "Password",
    emailPlaceholder: "example@email.com",
    passwordPlaceholder: "••••••",
    loginButton: "Login",
    registerButton: "Register",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?"
  },
  home: {
    title: "Remember everything you discover online",
    subtitle: "Accio organizes your online content with AI-powered tagging and powerful search.",
    getStarted: "Get Started - Free",
    howItWorks: "How Accio Works",
    tagline: "Your personal content library, organized by AI",
    nextButton: "Next",
    getStartedButton: "Get Started",
    features: {
      title: "Powerful Features",
      subtitle: "Accio brings powerful tools to help you organize and retrieve your digital content",
      search: {
        title: "Natural Language Search",
        description: "Ask questions in plain English like \"What did I save about job interviews?\" and Accio will find the right content."
      },
      tagging: {
        title: "AI-Powered Tagging",
        description: "Automatically categorize your content with relevant tags generated by advanced AI."
      },
      content: {
        title: "Multiple Content Types",
        description: "Save links, upload PDFs, or add images - all in one organized library."
      },
      saving: {
        title: "One-Click Saving",
        description: "Save content from anywhere with a simple click or share from other apps."
      }
    },
    cta: {
      title: "Ready to organize your online life?",
      subtitle: "Join Accio today and never lose important content again.",
      signUp: "Sign Up Free"
    },
    footer: {
      copyright: "© {{year}} Accio. All rights reserved."
    }
  },
  onboarding: {
    steps: {
      saveContent: {
        title: "Save Content",
        description: "Save articles, webpages, and files with a single click."
      },
      aiTagging: {
        title: "AI Tagging",
        description: "Accio automatically tags your content for easy organization."
      },
      uploadFiles: {
        title: "Upload Files",
        description: "Upload PDFs and images directly to your collection."
      },
      smartSearch: {
        title: "Smart Search",
        description: "Find content with keywords or natural language questions."
      }
    }
  }
};
